import { SidebarProvider } from "@/components/ui/sidebar";
import type { Metadata } from "next";
import { ThemeProvider } from "next-themes";

import { BigButtonBar, Workspaces } from "@/app/BigButtonBar";
import { JotaiProvider } from "@/app/JotaiProvider";
import { Geist, Geist_Mono } from "next/font/google";
import { cookies } from "next/headers";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const defaultOpen = cookieStore.get("sidebar:state")?.value === "true";
  const workspaces: Workspaces = [
    {
      name: "Workspace 1",
      href: "/workspace/WRK1",
    },
    {
      name: "Workspace 2",
      href: "/workspace/WRK2",
    },
    {
      name: "Workspace 3",
      href: "/workspace/WRK3",
    },
    {
      name: "Workspace 4",
      href: "/workspace/WRK4",
    },
  ];

  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <JotaiProvider>
          <SidebarProvider defaultOpen={defaultOpen}>
            <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
              <div className="w-full flex h-screen overflow-hidden">
                <BigButtonBar workspaces={workspaces} />
                {children}
              </div>
            </ThemeProvider>
          </SidebarProvider>
        </JotaiProvider>
      </body>
    </html>
  );
}
