/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PreviewRouteImport } from './routes/preview'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as PreviewSplatRouteImport } from './routes/preview/$'
import { Route as AppWorkspaceRouteImport } from './routes/_app/workspace'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppNewWorkspaceRouteImport } from './routes/_app/newWorkspace'
import { Route as AppConnectionsRouteImport } from './routes/_app/connections'
import { Route as AppWorkspaceWorkspaceIdRouteImport } from './routes/_app/workspace/$workspaceId'
import { Route as AppWorkspaceWorkspaceIdIndexRouteImport } from './routes/_app/workspace/$workspaceId/index'
import { Route as AppWorkspaceWorkspaceIdSettingsRouteImport } from './routes/_app/workspace/$workspaceId/settings'
import { Route as AppWorkspaceWorkspaceIdSplatRouteImport } from './routes/_app/workspace/$workspaceId.$'

const PreviewRoute = PreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const PreviewSplatRoute = PreviewSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => PreviewRoute,
} as any)
const AppWorkspaceRoute = AppWorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppNewWorkspaceRoute = AppNewWorkspaceRouteImport.update({
  id: '/newWorkspace',
  path: '/newWorkspace',
  getParentRoute: () => AppRoute,
} as any)
const AppConnectionsRoute = AppConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkspaceWorkspaceIdRoute = AppWorkspaceWorkspaceIdRouteImport.update({
  id: '/$workspaceId',
  path: '/$workspaceId',
  getParentRoute: () => AppWorkspaceRoute,
} as any)
const AppWorkspaceWorkspaceIdIndexRoute =
  AppWorkspaceWorkspaceIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppWorkspaceWorkspaceIdRoute,
  } as any)
const AppWorkspaceWorkspaceIdSettingsRoute =
  AppWorkspaceWorkspaceIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AppWorkspaceWorkspaceIdRoute,
  } as any)
const AppWorkspaceWorkspaceIdSplatRoute =
  AppWorkspaceWorkspaceIdSplatRouteImport.update({
    id: '/$',
    path: '/$',
    getParentRoute: () => AppWorkspaceWorkspaceIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/preview': typeof PreviewRouteWithChildren
  '/connections': typeof AppConnectionsRoute
  '/newWorkspace': typeof AppNewWorkspaceRoute
  '/settings': typeof AppSettingsRoute
  '/workspace': typeof AppWorkspaceRouteWithChildren
  '/preview/$': typeof PreviewSplatRoute
  '/': typeof AppIndexRoute
  '/workspace/$workspaceId': typeof AppWorkspaceWorkspaceIdRouteWithChildren
  '/workspace/$workspaceId/$': typeof AppWorkspaceWorkspaceIdSplatRoute
  '/workspace/$workspaceId/settings': typeof AppWorkspaceWorkspaceIdSettingsRoute
  '/workspace/$workspaceId/': typeof AppWorkspaceWorkspaceIdIndexRoute
}
export interface FileRoutesByTo {
  '/preview': typeof PreviewRouteWithChildren
  '/connections': typeof AppConnectionsRoute
  '/newWorkspace': typeof AppNewWorkspaceRoute
  '/settings': typeof AppSettingsRoute
  '/workspace': typeof AppWorkspaceRouteWithChildren
  '/preview/$': typeof PreviewSplatRoute
  '/': typeof AppIndexRoute
  '/workspace/$workspaceId/$': typeof AppWorkspaceWorkspaceIdSplatRoute
  '/workspace/$workspaceId/settings': typeof AppWorkspaceWorkspaceIdSettingsRoute
  '/workspace/$workspaceId': typeof AppWorkspaceWorkspaceIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/preview': typeof PreviewRouteWithChildren
  '/_app/connections': typeof AppConnectionsRoute
  '/_app/newWorkspace': typeof AppNewWorkspaceRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/workspace': typeof AppWorkspaceRouteWithChildren
  '/preview/$': typeof PreviewSplatRoute
  '/_app/': typeof AppIndexRoute
  '/_app/workspace/$workspaceId': typeof AppWorkspaceWorkspaceIdRouteWithChildren
  '/_app/workspace/$workspaceId/$': typeof AppWorkspaceWorkspaceIdSplatRoute
  '/_app/workspace/$workspaceId/settings': typeof AppWorkspaceWorkspaceIdSettingsRoute
  '/_app/workspace/$workspaceId/': typeof AppWorkspaceWorkspaceIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/preview'
    | '/connections'
    | '/newWorkspace'
    | '/settings'
    | '/workspace'
    | '/preview/$'
    | '/'
    | '/workspace/$workspaceId'
    | '/workspace/$workspaceId/$'
    | '/workspace/$workspaceId/settings'
    | '/workspace/$workspaceId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/preview'
    | '/connections'
    | '/newWorkspace'
    | '/settings'
    | '/workspace'
    | '/preview/$'
    | '/'
    | '/workspace/$workspaceId/$'
    | '/workspace/$workspaceId/settings'
    | '/workspace/$workspaceId'
  id:
    | '__root__'
    | '/_app'
    | '/preview'
    | '/_app/connections'
    | '/_app/newWorkspace'
    | '/_app/settings'
    | '/_app/workspace'
    | '/preview/$'
    | '/_app/'
    | '/_app/workspace/$workspaceId'
    | '/_app/workspace/$workspaceId/$'
    | '/_app/workspace/$workspaceId/settings'
    | '/_app/workspace/$workspaceId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  PreviewRoute: typeof PreviewRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/preview': {
      id: '/preview'
      path: '/preview'
      fullPath: '/preview'
      preLoaderRoute: typeof PreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/preview/$': {
      id: '/preview/$'
      path: '/$'
      fullPath: '/preview/$'
      preLoaderRoute: typeof PreviewSplatRouteImport
      parentRoute: typeof PreviewRoute
    }
    '/_app/workspace': {
      id: '/_app/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof AppWorkspaceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/newWorkspace': {
      id: '/_app/newWorkspace'
      path: '/newWorkspace'
      fullPath: '/newWorkspace'
      preLoaderRoute: typeof AppNewWorkspaceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/connections': {
      id: '/_app/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof AppConnectionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/workspace/$workspaceId': {
      id: '/_app/workspace/$workspaceId'
      path: '/$workspaceId'
      fullPath: '/workspace/$workspaceId'
      preLoaderRoute: typeof AppWorkspaceWorkspaceIdRouteImport
      parentRoute: typeof AppWorkspaceRoute
    }
    '/_app/workspace/$workspaceId/': {
      id: '/_app/workspace/$workspaceId/'
      path: '/'
      fullPath: '/workspace/$workspaceId/'
      preLoaderRoute: typeof AppWorkspaceWorkspaceIdIndexRouteImport
      parentRoute: typeof AppWorkspaceWorkspaceIdRoute
    }
    '/_app/workspace/$workspaceId/settings': {
      id: '/_app/workspace/$workspaceId/settings'
      path: '/settings'
      fullPath: '/workspace/$workspaceId/settings'
      preLoaderRoute: typeof AppWorkspaceWorkspaceIdSettingsRouteImport
      parentRoute: typeof AppWorkspaceWorkspaceIdRoute
    }
    '/_app/workspace/$workspaceId/$': {
      id: '/_app/workspace/$workspaceId/$'
      path: '/$'
      fullPath: '/workspace/$workspaceId/$'
      preLoaderRoute: typeof AppWorkspaceWorkspaceIdSplatRouteImport
      parentRoute: typeof AppWorkspaceWorkspaceIdRoute
    }
  }
}

interface AppWorkspaceWorkspaceIdRouteChildren {
  AppWorkspaceWorkspaceIdSplatRoute: typeof AppWorkspaceWorkspaceIdSplatRoute
  AppWorkspaceWorkspaceIdSettingsRoute: typeof AppWorkspaceWorkspaceIdSettingsRoute
  AppWorkspaceWorkspaceIdIndexRoute: typeof AppWorkspaceWorkspaceIdIndexRoute
}

const AppWorkspaceWorkspaceIdRouteChildren: AppWorkspaceWorkspaceIdRouteChildren =
  {
    AppWorkspaceWorkspaceIdSplatRoute: AppWorkspaceWorkspaceIdSplatRoute,
    AppWorkspaceWorkspaceIdSettingsRoute: AppWorkspaceWorkspaceIdSettingsRoute,
    AppWorkspaceWorkspaceIdIndexRoute: AppWorkspaceWorkspaceIdIndexRoute,
  }

const AppWorkspaceWorkspaceIdRouteWithChildren =
  AppWorkspaceWorkspaceIdRoute._addFileChildren(
    AppWorkspaceWorkspaceIdRouteChildren,
  )

interface AppWorkspaceRouteChildren {
  AppWorkspaceWorkspaceIdRoute: typeof AppWorkspaceWorkspaceIdRouteWithChildren
}

const AppWorkspaceRouteChildren: AppWorkspaceRouteChildren = {
  AppWorkspaceWorkspaceIdRoute: AppWorkspaceWorkspaceIdRouteWithChildren,
}

const AppWorkspaceRouteWithChildren = AppWorkspaceRoute._addFileChildren(
  AppWorkspaceRouteChildren,
)

interface AppRouteChildren {
  AppConnectionsRoute: typeof AppConnectionsRoute
  AppNewWorkspaceRoute: typeof AppNewWorkspaceRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppWorkspaceRoute: typeof AppWorkspaceRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppConnectionsRoute: AppConnectionsRoute,
  AppNewWorkspaceRoute: AppNewWorkspaceRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppWorkspaceRoute: AppWorkspaceRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface PreviewRouteChildren {
  PreviewSplatRoute: typeof PreviewSplatRoute
}

const PreviewRouteChildren: PreviewRouteChildren = {
  PreviewSplatRoute: PreviewSplatRoute,
}

const PreviewRouteWithChildren =
  PreviewRoute._addFileChildren(PreviewRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  PreviewRoute: PreviewRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
