/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PreviewRouteImport } from './routes/preview'
import { Route as AllSettingsRouteImport } from './routes/all-settings'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as PreviewSplatRouteImport } from './routes/preview/$'
import { Route as AuthNetlifyRouteImport } from './routes/auth.netlify'
import { Route as AuthGithubRouteImport } from './routes/auth.github'
import { Route as AllSettingsSplatRouteImport } from './routes/all-settings/$'
import { Route as AppWorkspaceRouteImport } from './routes/_app/workspace'
import { Route as AppThemesRouteImport } from './routes/_app/themes'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppSandboxRouteImport } from './routes/_app/sandbox'
import { Route as AppNewWorkspaceRouteImport } from './routes/_app/newWorkspace'
import { Route as AppConnectionsRouteImport } from './routes/_app/connections'
import { Route as AppWorkspaceWorkspaceNameRouteImport } from './routes/_app/workspace/$workspaceName'
import { Route as AppWorkspaceWorkspaceNameIndexRouteImport } from './routes/_app/workspace/$workspaceName/index'
import { Route as AppWorkspaceWorkspaceNameSettingsRouteImport } from './routes/_app/workspace/$workspaceName/settings'
import { Route as AppWorkspaceWorkspaceNameSplatRouteImport } from './routes/_app/workspace/$workspaceName.$'

const PreviewRoute = PreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const AllSettingsRoute = AllSettingsRouteImport.update({
  id: '/all-settings',
  path: '/all-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const PreviewSplatRoute = PreviewSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => PreviewRoute,
} as any)
const AuthNetlifyRoute = AuthNetlifyRouteImport.update({
  id: '/auth/netlify',
  path: '/auth/netlify',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthGithubRoute = AuthGithubRouteImport.update({
  id: '/auth/github',
  path: '/auth/github',
  getParentRoute: () => rootRouteImport,
} as any)
const AllSettingsSplatRoute = AllSettingsSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AllSettingsRoute,
} as any)
const AppWorkspaceRoute = AppWorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => AppRoute,
} as any)
const AppThemesRoute = AppThemesRouteImport.update({
  id: '/themes',
  path: '/themes',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSandboxRoute = AppSandboxRouteImport.update({
  id: '/sandbox',
  path: '/sandbox',
  getParentRoute: () => AppRoute,
} as any)
const AppNewWorkspaceRoute = AppNewWorkspaceRouteImport.update({
  id: '/newWorkspace',
  path: '/newWorkspace',
  getParentRoute: () => AppRoute,
} as any)
const AppConnectionsRoute = AppConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkspaceWorkspaceNameRoute =
  AppWorkspaceWorkspaceNameRouteImport.update({
    id: '/$workspaceName',
    path: '/$workspaceName',
    getParentRoute: () => AppWorkspaceRoute,
  } as any)
const AppWorkspaceWorkspaceNameIndexRoute =
  AppWorkspaceWorkspaceNameIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppWorkspaceWorkspaceNameRoute,
  } as any)
const AppWorkspaceWorkspaceNameSettingsRoute =
  AppWorkspaceWorkspaceNameSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AppWorkspaceWorkspaceNameRoute,
  } as any)
const AppWorkspaceWorkspaceNameSplatRoute =
  AppWorkspaceWorkspaceNameSplatRouteImport.update({
    id: '/$',
    path: '/$',
    getParentRoute: () => AppWorkspaceWorkspaceNameRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/all-settings': typeof AllSettingsRouteWithChildren
  '/preview': typeof PreviewRouteWithChildren
  '/connections': typeof AppConnectionsRoute
  '/newWorkspace': typeof AppNewWorkspaceRoute
  '/sandbox': typeof AppSandboxRoute
  '/settings': typeof AppSettingsRoute
  '/themes': typeof AppThemesRoute
  '/workspace': typeof AppWorkspaceRouteWithChildren
  '/all-settings/$': typeof AllSettingsSplatRoute
  '/auth/github': typeof AuthGithubRoute
  '/auth/netlify': typeof AuthNetlifyRoute
  '/preview/$': typeof PreviewSplatRoute
  '/': typeof AppIndexRoute
  '/workspace/$workspaceName': typeof AppWorkspaceWorkspaceNameRouteWithChildren
  '/workspace/$workspaceName/$': typeof AppWorkspaceWorkspaceNameSplatRoute
  '/workspace/$workspaceName/settings': typeof AppWorkspaceWorkspaceNameSettingsRoute
  '/workspace/$workspaceName/': typeof AppWorkspaceWorkspaceNameIndexRoute
}
export interface FileRoutesByTo {
  '/all-settings': typeof AllSettingsRouteWithChildren
  '/preview': typeof PreviewRouteWithChildren
  '/connections': typeof AppConnectionsRoute
  '/newWorkspace': typeof AppNewWorkspaceRoute
  '/sandbox': typeof AppSandboxRoute
  '/settings': typeof AppSettingsRoute
  '/themes': typeof AppThemesRoute
  '/workspace': typeof AppWorkspaceRouteWithChildren
  '/all-settings/$': typeof AllSettingsSplatRoute
  '/auth/github': typeof AuthGithubRoute
  '/auth/netlify': typeof AuthNetlifyRoute
  '/preview/$': typeof PreviewSplatRoute
  '/': typeof AppIndexRoute
  '/workspace/$workspaceName/$': typeof AppWorkspaceWorkspaceNameSplatRoute
  '/workspace/$workspaceName/settings': typeof AppWorkspaceWorkspaceNameSettingsRoute
  '/workspace/$workspaceName': typeof AppWorkspaceWorkspaceNameIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/all-settings': typeof AllSettingsRouteWithChildren
  '/preview': typeof PreviewRouteWithChildren
  '/_app/connections': typeof AppConnectionsRoute
  '/_app/newWorkspace': typeof AppNewWorkspaceRoute
  '/_app/sandbox': typeof AppSandboxRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/themes': typeof AppThemesRoute
  '/_app/workspace': typeof AppWorkspaceRouteWithChildren
  '/all-settings/$': typeof AllSettingsSplatRoute
  '/auth/github': typeof AuthGithubRoute
  '/auth/netlify': typeof AuthNetlifyRoute
  '/preview/$': typeof PreviewSplatRoute
  '/_app/': typeof AppIndexRoute
  '/_app/workspace/$workspaceName': typeof AppWorkspaceWorkspaceNameRouteWithChildren
  '/_app/workspace/$workspaceName/$': typeof AppWorkspaceWorkspaceNameSplatRoute
  '/_app/workspace/$workspaceName/settings': typeof AppWorkspaceWorkspaceNameSettingsRoute
  '/_app/workspace/$workspaceName/': typeof AppWorkspaceWorkspaceNameIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/all-settings'
    | '/preview'
    | '/connections'
    | '/newWorkspace'
    | '/sandbox'
    | '/settings'
    | '/themes'
    | '/workspace'
    | '/all-settings/$'
    | '/auth/github'
    | '/auth/netlify'
    | '/preview/$'
    | '/'
    | '/workspace/$workspaceName'
    | '/workspace/$workspaceName/$'
    | '/workspace/$workspaceName/settings'
    | '/workspace/$workspaceName/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/all-settings'
    | '/preview'
    | '/connections'
    | '/newWorkspace'
    | '/sandbox'
    | '/settings'
    | '/themes'
    | '/workspace'
    | '/all-settings/$'
    | '/auth/github'
    | '/auth/netlify'
    | '/preview/$'
    | '/'
    | '/workspace/$workspaceName/$'
    | '/workspace/$workspaceName/settings'
    | '/workspace/$workspaceName'
  id:
    | '__root__'
    | '/_app'
    | '/all-settings'
    | '/preview'
    | '/_app/connections'
    | '/_app/newWorkspace'
    | '/_app/sandbox'
    | '/_app/settings'
    | '/_app/themes'
    | '/_app/workspace'
    | '/all-settings/$'
    | '/auth/github'
    | '/auth/netlify'
    | '/preview/$'
    | '/_app/'
    | '/_app/workspace/$workspaceName'
    | '/_app/workspace/$workspaceName/$'
    | '/_app/workspace/$workspaceName/settings'
    | '/_app/workspace/$workspaceName/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AllSettingsRoute: typeof AllSettingsRouteWithChildren
  PreviewRoute: typeof PreviewRouteWithChildren
  AuthGithubRoute: typeof AuthGithubRoute
  AuthNetlifyRoute: typeof AuthNetlifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/preview': {
      id: '/preview'
      path: '/preview'
      fullPath: '/preview'
      preLoaderRoute: typeof PreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/all-settings': {
      id: '/all-settings'
      path: '/all-settings'
      fullPath: '/all-settings'
      preLoaderRoute: typeof AllSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/preview/$': {
      id: '/preview/$'
      path: '/$'
      fullPath: '/preview/$'
      preLoaderRoute: typeof PreviewSplatRouteImport
      parentRoute: typeof PreviewRoute
    }
    '/auth/netlify': {
      id: '/auth/netlify'
      path: '/auth/netlify'
      fullPath: '/auth/netlify'
      preLoaderRoute: typeof AuthNetlifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/github': {
      id: '/auth/github'
      path: '/auth/github'
      fullPath: '/auth/github'
      preLoaderRoute: typeof AuthGithubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/all-settings/$': {
      id: '/all-settings/$'
      path: '/$'
      fullPath: '/all-settings/$'
      preLoaderRoute: typeof AllSettingsSplatRouteImport
      parentRoute: typeof AllSettingsRoute
    }
    '/_app/workspace': {
      id: '/_app/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof AppWorkspaceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/themes': {
      id: '/_app/themes'
      path: '/themes'
      fullPath: '/themes'
      preLoaderRoute: typeof AppThemesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sandbox': {
      id: '/_app/sandbox'
      path: '/sandbox'
      fullPath: '/sandbox'
      preLoaderRoute: typeof AppSandboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/newWorkspace': {
      id: '/_app/newWorkspace'
      path: '/newWorkspace'
      fullPath: '/newWorkspace'
      preLoaderRoute: typeof AppNewWorkspaceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/connections': {
      id: '/_app/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof AppConnectionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/workspace/$workspaceName': {
      id: '/_app/workspace/$workspaceName'
      path: '/$workspaceName'
      fullPath: '/workspace/$workspaceName'
      preLoaderRoute: typeof AppWorkspaceWorkspaceNameRouteImport
      parentRoute: typeof AppWorkspaceRoute
    }
    '/_app/workspace/$workspaceName/': {
      id: '/_app/workspace/$workspaceName/'
      path: '/'
      fullPath: '/workspace/$workspaceName/'
      preLoaderRoute: typeof AppWorkspaceWorkspaceNameIndexRouteImport
      parentRoute: typeof AppWorkspaceWorkspaceNameRoute
    }
    '/_app/workspace/$workspaceName/settings': {
      id: '/_app/workspace/$workspaceName/settings'
      path: '/settings'
      fullPath: '/workspace/$workspaceName/settings'
      preLoaderRoute: typeof AppWorkspaceWorkspaceNameSettingsRouteImport
      parentRoute: typeof AppWorkspaceWorkspaceNameRoute
    }
    '/_app/workspace/$workspaceName/$': {
      id: '/_app/workspace/$workspaceName/$'
      path: '/$'
      fullPath: '/workspace/$workspaceName/$'
      preLoaderRoute: typeof AppWorkspaceWorkspaceNameSplatRouteImport
      parentRoute: typeof AppWorkspaceWorkspaceNameRoute
    }
  }
}

interface AppWorkspaceWorkspaceNameRouteChildren {
  AppWorkspaceWorkspaceNameSplatRoute: typeof AppWorkspaceWorkspaceNameSplatRoute
  AppWorkspaceWorkspaceNameSettingsRoute: typeof AppWorkspaceWorkspaceNameSettingsRoute
  AppWorkspaceWorkspaceNameIndexRoute: typeof AppWorkspaceWorkspaceNameIndexRoute
}

const AppWorkspaceWorkspaceNameRouteChildren: AppWorkspaceWorkspaceNameRouteChildren =
  {
    AppWorkspaceWorkspaceNameSplatRoute: AppWorkspaceWorkspaceNameSplatRoute,
    AppWorkspaceWorkspaceNameSettingsRoute:
      AppWorkspaceWorkspaceNameSettingsRoute,
    AppWorkspaceWorkspaceNameIndexRoute: AppWorkspaceWorkspaceNameIndexRoute,
  }

const AppWorkspaceWorkspaceNameRouteWithChildren =
  AppWorkspaceWorkspaceNameRoute._addFileChildren(
    AppWorkspaceWorkspaceNameRouteChildren,
  )

interface AppWorkspaceRouteChildren {
  AppWorkspaceWorkspaceNameRoute: typeof AppWorkspaceWorkspaceNameRouteWithChildren
}

const AppWorkspaceRouteChildren: AppWorkspaceRouteChildren = {
  AppWorkspaceWorkspaceNameRoute: AppWorkspaceWorkspaceNameRouteWithChildren,
}

const AppWorkspaceRouteWithChildren = AppWorkspaceRoute._addFileChildren(
  AppWorkspaceRouteChildren,
)

interface AppRouteChildren {
  AppConnectionsRoute: typeof AppConnectionsRoute
  AppNewWorkspaceRoute: typeof AppNewWorkspaceRoute
  AppSandboxRoute: typeof AppSandboxRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppThemesRoute: typeof AppThemesRoute
  AppWorkspaceRoute: typeof AppWorkspaceRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppConnectionsRoute: AppConnectionsRoute,
  AppNewWorkspaceRoute: AppNewWorkspaceRoute,
  AppSandboxRoute: AppSandboxRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppThemesRoute: AppThemesRoute,
  AppWorkspaceRoute: AppWorkspaceRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AllSettingsRouteChildren {
  AllSettingsSplatRoute: typeof AllSettingsSplatRoute
}

const AllSettingsRouteChildren: AllSettingsRouteChildren = {
  AllSettingsSplatRoute: AllSettingsSplatRoute,
}

const AllSettingsRouteWithChildren = AllSettingsRoute._addFileChildren(
  AllSettingsRouteChildren,
)

interface PreviewRouteChildren {
  PreviewSplatRoute: typeof PreviewSplatRoute
}

const PreviewRouteChildren: PreviewRouteChildren = {
  PreviewSplatRoute: PreviewSplatRoute,
}

const PreviewRouteWithChildren =
  PreviewRoute._addFileChildren(PreviewRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AllSettingsRoute: AllSettingsRouteWithChildren,
  PreviewRoute: PreviewRouteWithChildren,
  AuthGithubRoute: AuthGithubRoute,
  AuthNetlifyRoute: AuthNetlifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
